version: "3.7"

services:

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  letsencrypt:
    extends:
      file: docker-compose.yml
      service: letsencrypt

  php:
    extends:
      file: docker-compose.yml
      service: php

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  memcached:
    extends:
      file: docker-compose.yml
      service: memcached

  mailhog:
    extends:
      file: docker-compose.yml
      service: mailhog

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

volumes:
  letsencrypt_certs:
  letsencrypt_www:
  memcached_socket:
  php_socket:
  mysql_socket:
  redis_socket:
  elastic_data:
  redis_data:
  mysql_data:
  app_data:
    external: true