version: "3.7"

services:

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  letsencrypt:
    extends:
      file: docker-compose.yml
      service: letsencrypt

  php:
    extends:
      file: docker-compose.yml
      service: php

  cron:
    extends:
      file: docker-compose.yml
      service: cron

  image_optimizer:
    extends:
      file: docker-compose.yml
      service: cron

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql

  redis_cache:
    extends:
      file: docker-compose.yml
      service: redis_cache

  redis_session:
    extends:
      file: docker-compose.yml
      service: redis_session

  mailhog:
    extends:
      file: docker-compose.yml
      service: mailhog

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

volumes:
  php_crontabs:
  letsencrypt_certs:
  letsencrypt_www:
  memcached_socket:
  php_socket:
  mysql_socket:
  redis_cache_socket:
  redis_session_socket:
  elastic_data:
  redis_cache_data:
  redis_session_data:
  mysql_data:
  pagespeed_cache:
    driver_opts:
      type: tmpfs
      device: tmpfs
  app_data:
    external: true
