version: "3.7"

services:

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - lets_encrypt_data:/etc/nginx/ssl
      
volumes:
  lets_encrypt_data:
    driver: local