version: "3.7"

services:

  nginx:
    build:
      context: ./.docker/nginx
      args:
        TZ: ${TZ}
        USERNAME: ${USERNAME}
        WORKDIR_SERVER: ${WORKDIR_SERVER}
        SHOP_URI: ${SHOP_URI}
        AUTH_CONFIG: ${AUTH_CONFIG}
        AUTH_USER: ${AUTH_USER}
        AUTH_PASS: ${AUTH_PASS}
    container_name: ${NAMESPACE}_nginx
    image: ${NAMESPACE}/nginx
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - php_socket:/var/run/php
      - pagespeed_cache:/var/cache/ngx_pagespeed

  php:
    build:
      context: ./.docker/php
      args:
        TZ: ${TZ}
        PHP_VERSION_SET_IMAGE: php:${PHP_VERSION_SET}-fpm-alpine
        PHP_VERSION_SET: ${PHP_VERSION_SET}
        USERNAME: ${USERNAME}
        WORKDIR_SERVER: ${WORKDIR_SERVER}
        XDEBUG_ENABLE: ${XDEBUG_ENABLE}
        INSTALL_MAGENTO: ${INSTALL_MAGENTO}
        INSTALL_MAGENTO_VERSION: ${INSTALL_MAGENTO_VERSION}
        INSTALL_SAMPLE_DATA: ${INSTALL_SAMPLE_DATA}
        COMPOSER_UPDATE_ON_START: ${COMPOSER_UPDATE_ON_START}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        SHOP_URI: ${SHOP_URI}
    container_name: ${NAMESPACE}_php
    image: ${NAMESPACE}/php:${PHP_VERSION_SET}-fpm-alpine
    sysctls:
      net.core.somaxconn: '65536'
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - mysql
#    command: [magento-install.sh
#      $INSTALL_MAGENTO,
#      $USERNAME,
#      $WORKDIR_SERVER,
#      $INSTALL_MAGENTO_VERSION,
#      $INSTALL_SAMPLE_DATA,
#      $COMPOSER_UPDATE_ON_START,
#      $XDEBUG_ENABLE,
#      $MYSQL_DATABASE,
#      $MYSQL_USER,
#      $MYSQL_PASSWORD,
#      $SHOP_URI
#    ]
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - php_socket:/var/run/php
      - mysql_socket:/var/run/mysqld

  mysql:
    build:
      context: ./.docker/mysql
      args:
        USERNAME: ${USERNAME}
        TZ: ${TZ}
    container_name: ${NAMESPACE}_mysql
    image: ${NAMESPACE}/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_vol:/var/lib/mysql/
      - mysql_socket:/var/run/mysqld
      - .docker/mysql/db_dumps:/docker-entrypoint-initdb.d/

  redis_cache:
    build:
      context: ./.docker/redis
      args:
        USERNAME: ${USERNAME}
        TZ: ${TZ}
    container_name: ${NAMESPACE}_redis_cache
    image: ${NAMESPACE}/redis_cache
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redis_cache_data:/data

  redis_pagespeed_cache:
    build:
      context: ./.docker/redis
      args:
        USERNAME: ${USERNAME}
        TZ: ${TZ}
    container_name: ${NAMESPACE}_redis_pagespeed_cache
    image: ${NAMESPACE}/redis_pagespeed_cache
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redis_pagespeed_cache_data:/data

  redis_page_cache:
    build:
      context: ./.docker/redis
      args:
        USERNAME: ${USERNAME}
        TZ: ${TZ}
    container_name: ${NAMESPACE}_redis_page_cache
    image: ${NAMESPACE}/redis_page_cache
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redis_page_cache_data:/data

  redis_session:
    build:
      context: ./.docker/redis
      args:
        USERNAME: ${USERNAME}
        TZ: ${TZ}
    container_name: ${NAMESPACE}_redis_session
    image: ${NAMESPACE}/redis_session
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redis_session_data:/data

  mailhog:
    container_name: ${NAMESPACE}_mailhog
    image: mailhog/mailhog:latest
    expose:
      - 1025
    ports:
      - 8025:8025
      - 1025:1025

  elasticsearch:
    build:
      context: ./.docker/elasticsearch
      args:
        TZ: ${TZ}
    container_name: ${NAMESPACE}_elasticsearch
    image: ${NAMESPACE}/elasticsearch:5.2
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  letsencrypt:
    container_name: ${NAMESPACE}_letsencrypt
    build:
      context: ./.docker/letsencrypt
      args:
        SHOP_URI: ${SHOP_URI}
    image: ${NAMESPACE}/letsencrypt
    command: /bin/true
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt

volumes:
  php_socket:
    driver_opts:
      type: tmpfs
      device: tmpfs
  mysql_vol:
  mysql_socket:
    driver_opts:
      type: tmpfs
      device: tmpfs
  letsencrypt_certs:
  letsencrypt_www:
  elastic_data:
  redis_cache_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  redis_page_cache_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  redis_session_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  pagespeed_cache:
    driver_opts:
      type: tmpfs
      device: tmpfs
  redis_pagespeed_cache_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
  app_data:
    driver_opts:
      type: none
      o: bind
      device: "${WORKDIR}"
