version: "3.7"

services:

  nginx:
    container_name: ${NAMESPACE}_nginx
    build:
      context: ./.docker/nginx
      args:
        USERNAME: ${USERNAME}
        WORKDIR_SERVER: ${WORKDIR_SERVER}
        SHOP_URI: ${SHOP_URI}
        AUTH_CONFIG: ${AUTH_CONFIG}
        AUTH_USER: ${AUTH_USER}
        AUTH_PASS: ${AUTH_PASS}
    image: ${NAMESPACE}/nginx
    restart: always
    #image: ${DOCKER_REGISTRY}/nginx
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - phpsocket:/var/run
      - letsencrypt_certs:/etc/nginx/certs
      - letsencrypt_www:/var/www/letsencrypt
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${SUB_DOMAIN}
      - LETSENCRYPT_EMAIL=${MAIL}

  letsencrypt:
    container_name: ${NAMESPACE}_letsencrypt
    build:
      context: ./.docker/letsencrypt
      args:
        SHOP_URI: ${SHOP_URI}
    image: ${NAMESPACE}/letsencrypt
    #image: ${DOCKER_REGISTRY}/letsencrypt
    restart: always
    command: /bin/true
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt

  php:
    container_name: ${NAMESPACE}_php
    build:
      context: ./.docker/php
      args:
        PHP_VERSION_SET_IMAGE: php:${PHP_VERSION_SET}-fpm-alpine3.7
        PHP_VERSION_SET: ${PHP_VERSION_SET}
        USERNAME: ${USERNAME}
        WORKDIR_SERVER: ${WORKDIR_SERVER}
        INSTALL_MAGENTO: ${INSTALL_MAGENTO}
        INSTALL_MAGENTO_VERSION: ${INSTALL_MAGENTO_VERSION}
        INSTALL_SAMPLE_DATA: ${INSTALL_SAMPLE_DATA}
    image: ${NAMESPACE}/php:${PHP_VERSION_SET}_magento-installed_${INSTALL_MAGENTO}
    #image: ${DOCKER_REGISTRY}/php:${PHP_VERSION_SET}_magento-installed_${INSTALL_MAGENTO}
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - mysql
      - redis
      - elasticsearch
    links:
      - mailhog
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - phpsocket:/var/run
      - redissocket:/var/redis
      - mysqlsocket:/var/run/mysqld

  mysql:
    container_name: ${NAMESPACE}_mysql
    build:
      context: ./.docker/mysql
      args:
        USERNAME: ${USERNAME}
    image: ${NAMESPACE}/mysql
    #image: ${DOCKER_REGISTRY}/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql:cached
      - mysqlsocket:/var/run/mysqld

  redis:
    container_name: ${NAMESPACE}_redis
    build:
      context: ./.docker/redis
      args:
       USERNAME: ${USERNAME}
    image: ${NAMESPACE}/redis
    #image: ${DOCKER_REGISTRY}/redis
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redissocket:/var/redis
      - redis_data:/data:cached

  mailhog:
    container_name: ${NAMESPACE}_mailhog
    image: mailhog/mailhog:latest
    expose:
      - 1025
    ports:
      - 8025:8025

  elasticsearch:
    build:
      context: ./.docker/elasticsearch
      args:
        ELASTICSEARCH_VERSION:
    image: ${NAMESPACE}/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: ${NAMESPACE}_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  letsencrypt_certs: ~
  letsencrypt_www: ~
  phpsocket:
  mysqlsocket:
  redissocket:
  elastic_data:
    driver: local
  redis_data:
    driver: local
  mysql_data:
    driver: local
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${WORKDIR}"