version: "3.7"

services:

  nginx:
    container_name: ${NAMESPACE}_nginx
    image: ${NAMESPACE}/nginx
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - php
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - php_socket:/var/run
      - letsencrypt_certs:/etc/nginx/certs
      - letsencrypt_www:/var/www/letsencrypt

  letsencrypt:
    container_name: ${NAMESPACE}_letsencrypt
    image: ${NAMESPACE}/letsencrypt
    command: /bin/true
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt

  php:
    container_name: ${NAMESPACE}_php
    image: ${NAMESPACE}/php:${PHP_VERSION_SET}-fpm-alpine
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - mysql
      - redis
      - elasticsearch
    links:
      - mailhog
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - php_crontabs:/etc/crontabs
      - php_socket:/var/run
      - redis_socket:/var/redis
      - mysql_socket:/var/run/mysqld/

  mysql:
    container_name: ${NAMESPACE}_mysql
    image: ${NAMESPACE}/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_socket:/var/run/mysqld/
      - .docker/mysql/db-dumps:/docker-entrypoint-initdb.d

  redis:
    container_name: ${NAMESPACE}_redis
    image: ${NAMESPACE}/redis
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redis_socket:/var/redis
      - redis_data:/data

  memcached:
    container_name: ${NAMESPACE}_memcached
    image: memcached:alpine
    volumes:
      - memcached_socket:/var/run/

  mailhog:
    container_name: ${NAMESPACE}_mailhog
    image: mailhog/mailhog:latest
    expose:
      - 1025
    ports:
      - 8025:8025

  elasticsearch:
    image: ${NAMESPACE}/elasticsearch:5.2
    container_name: ${NAMESPACE}_elasticsearch_5.2
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  php_crontabs:
  letsencrypt_certs:
  letsencrypt_www:
  memcached_socket:
  php_socket:
  mysql_socket:
  redis_socket:
  elastic_data:
  redis_data:
  mysql_data:
  app_data:
    driver_opts:
      type: none
      o: bind
      device: "${WORKDIR}"