version: "3.7"

services:
  nginx:
    build: ./nginx
    #image: osioaliu/nginx
    container_name: ${NAMESPACE}_nginx
    image: ${NAMESPACE}/nginx
    depends_on:
      - php
    working_dir: ${WORKDIR_SERVER}
    ports:
      - 80:80
      - 443:443
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated

  php:
    build:
      context: ./php
      args:
        PHP_VERSION_SET: ${PHP_VERSION_SET}
        PHP_VERSION_SET_IMAGE: php:${PHP_VERSION_SET}-fpm-alpine3.8
    #image: osiolaliu/php_7.1
    image: ${NAMESPACE}/php_${PHP_VERSION_SET}
    container_name: ${NAMESPACE}_php_${PHP_VERSION_SET}
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - mysql
      - redis
      - mailhog
      - elasticsearch
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated

  elasticsearch:
    image: elasticsearch:5.6-alpine
    container_name: ${NAMESPACE}_elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
 
  mysql:
    build: ./mysql
    #image: osiolaliu/mysql
    container_name: ${NAMESPACE}_mysql
    image: ${NAMESPACE}/mysql
    ports:
      - ${DATABASE_PORT_EXTERNAL}:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    build: ./redis
    #image: osiolaliu/redis
    container_name: ${NAMESPACE}_redis
    image: ${NAMESPACE}/redis
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: '1024'

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${NAMESPACE}_mailhog
    expose:
      - 1025
    ports:
      - 8025:8025

volumes:
  mysql_data:
    driver: local
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${WORKDIR}"