version: "3.7"

services:

  nginx:
    build:
      context: ./nginx
      args:
        USER: ${USER}
        WORKDIR_SERVER: ${WORKDIR_SERVER}
        SHOP_URI: ${SHOP_URI}
    #image: osioaliu/nginx
    container_name: ${NAMESPACE}_nginx
    image: ${NAMESPACE}/nginx
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - phpsocket:/var/run
    networks:
      - backend
      - frontend

  php:
    build:
      context: ./php
      args:
        PHP_VERSION_SET_IMAGE: php:${PHP_VERSION_SET}-fpm-alpine3.8
        USER: ${USER}
        WORKDIR_SERVER: ${WORKDIR_SERVER}
    #image: osiolaliu/php_7.1
    image: ${NAMESPACE}/php_${PHP_VERSION_SET}
    container_name: ${NAMESPACE}_php
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - mysql
      - mailhog
      - elasticsearch
      - redis
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - phpsocket:/var/run
      - redissocket:/var/redis
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:5.6-alpine
    container_name: ${NAMESPACE}_elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  mysql:
    build: ./mysql
    #image: osiolaliu/mysql
    container_name: ${NAMESPACE}_mysql
    image: ${NAMESPACE}/mysql
    ports:
      - ${DATABASE_PORT_EXTERNAL}:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    build:
      context: ./redis
      args:
        USER: ${USER}
    #image: osiolaliu/redis
    container_name: ${NAMESPACE}_redis
    image: ${NAMESPACE}/redis
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redissocket:/var/redis
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${NAMESPACE}_mailhog
    expose:
      - 1025
    ports:
      - 8025:8025
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  redissocket:
  phpsocket:
  mysql_data:
    driver: local
  app_data:
    external: true